#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2017 Magenta ApS <info@magenta.dk>
#
# SPDX-License-Identifier: GPL-3.0-or-later
#
# SPDX-FileContributor: Danni Als, Alexander Faithfull, Carsten Agger, Marcus Funch, Søren Howe Gersager, Andreas Poulsen

"""Security Script for finding USB keyboard attachment events."""

import sys
import os
from datetime import datetime, timedelta
import re

__copyright__ = "Copyright 2017-2024 Magenta ApS"
__license__ = "GPL-3.0-or-later"


def log_read(last_security_check, log_name):
    """Search a (system) log for events that occurred between "last_security_check" and now."""
    log_event_tuples = []
    now = datetime.now()

    with open(log_name) as f:
        for line in f.readlines():
            line = line.replace("\0", "").strip("\n")
            try:
                log_event_timestamp = line[:15]
                log_event = line
                # convert from log event timestamp to security event log timestamp.
                log_event_datetime = datetime.strptime(
                    str(now.year) + " " + log_event_timestamp, "%Y %b  %d %H:%M:%S"
                )
            except ValueError:
                log_event_timestamp = line[:19]
                log_event = line
                # convert from log event timestamp to security event log timestamp.
                log_event_datetime = datetime.strptime(
                    log_event_timestamp, "%Y-%m-%dT%H:%M:%S"
                )
            security_event_log_timestamp = datetime.strftime(
                log_event_datetime, "%Y%m%d%H%M%S"
            )
            # Detect lines from within the last x seconds to now.
            if last_security_check <= log_event_datetime <= now:
                log_event_tuples.append((security_event_log_timestamp, log_event))

    return log_event_tuples


def csv_writer(security_events):
    """Write security events to security events file."""
    with open("/etc/os2borgerpc/security/securityevent.csv", "at") as csvfile:
        for timestamp, security_problem_uid, log_event in security_events:
            event_line = log_event.replace("\n", " ").replace("\r", "").replace(",", "")
            csvfile.write(f"{timestamp},{security_problem_uid},{event_line}\n")


def filter_duplicate_events(security_events):
    """Filter duplicate events related to the same keyboard."""
    unique_tuples = []
    unique_keyboards = []

    for security_event in security_events:
        # This identifier is based on the ID of the USB device.
        # The ID is identical for identical USB devices so
        # if two identical keyboards are inserted simultaneously,
        # only one event will be generated.
        regex = (
            r"[0-9a-z]{4}:[0-9a-z]{4}:[0-9a-z]{4}"
            r"(?!.*/[0-9a-z]{4}:[0-9a-z]{4}:[0-9a-z]{4})"
        )
        match = re.search(regex, security_event[2], flags=re.IGNORECASE)
        # Keyboard event lines should always contain a match, but in order
        # to prevent possibly overlooking a relevant event, we always include
        # events with no match, except if they contain "gdm-x-session".
        # We disregard lines with no match that contain "gdm-x-session"
        # because they are generated by gdm every time a user logs in or out.
        # The actual lines that we want to match do not contain "gdm-x-session".
        if match:
            keyboard_identifier = match.group(0)
            if keyboard_identifier not in unique_keyboards:
                unique_tuples.append(security_event)
                unique_keyboards.append(keyboard_identifier)
        elif "gdm-x-session" not in security_event[2]:
            unique_tuples.append(security_event)

    return unique_tuples


def filter_boot_events(security_events, last_security_check):
    """Filter events related to boot."""
    boot_event_period = 60  # This is in seconds
    real_security_events = []

    boot_times = os.popen("journalctl --list-boots | tail -2").read()[:-1].split("\n")

    current_boot_time = boot_times[-1].split(" 0 ")[1].split(" ")
    current_boot_time = datetime.strptime(
        f"{current_boot_time[2]} {current_boot_time[3]}", "%Y-%m-%d %H:%M:%S"
    )

    # If last_security_check was after boot, we can't possibly have any boot events
    if last_security_check > current_boot_time:
        return security_events

    current_boot_event_limit = current_boot_time + timedelta(seconds=boot_event_period)

    if len(boot_times) == 2:
        previous_boot_time = boot_times[-2].split(" -1 ")[1].split(" ")
        previous_boot_time = datetime.strptime(
            f"{previous_boot_time[2]} {previous_boot_time[3]}", "%Y-%m-%d %H:%M:%S"
        )

        previous_boot_event_limit = previous_boot_time + timedelta(
            seconds=boot_event_period
        )

    for security_event in security_events:
        security_event_timestamp = datetime.strptime(security_event[0], "%Y%m%d%H%M%S")
        if not (
            current_boot_event_limit > security_event_timestamp > current_boot_time
            or (
                len(boot_times) == 2
                and previous_boot_event_limit
                > security_event_timestamp
                > previous_boot_time
            )
        ):
            real_security_events.append(security_event)

    return real_security_events


# The file to inspect for events
log_name = "/var/log/syslog"

now = datetime.now()
# The default value in case lastcheck.txt is nonexisting or empty:
last_security_check = now - timedelta(hours=24)
try:
    with open("/etc/os2borgerpc/security/lastcheck.txt", "r") as fp:
        timestamp = fp.read()
        if timestamp:
            last_security_check = datetime.strptime(timestamp, "%Y%m%d%H%M%S")
except IOError:
    pass

log_event_tuples = log_read(last_security_check, log_name)

security_problem_uid_template_var = "%SECURITY_PROBLEM_UID%"

# Match keyboard events that are after 9.9999 seconds of boot up
# (so we don't match upstart keyboard events),
# Also remove system control and consumer control entries:
# The reason is that some keyboards add three keyboard entries when connected.
# Example from inserting a keyboard once:
# Jun 28 14:24:43 kbh-nuc-venstre kernel: [ 1948.130701] input: Logitech HID compliant keyboard as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0/0003:046D:C30E.000A/input/input25
# Jun 28 14:24:43 kbh-nuc-venstre kernel: [ 1948.264053] input: Logitech HID compliant keyboard System Control as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.1/0003:046D:C30E.000B/input/input27
# Jun 28 14:24:43 kbh-nuc-venstre kernel: [ 1948.204460] input: Logitech HID compliant keyboard Consumer Control as /devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.1/0003:046D:C30E.000B/input/input26
# Fortunately it seems Consumer Control and System Control aren't Logitech specific, as we've seen the exact same with Lenovo keyboards.
# The second regex matches certain keyboards that do not generate a log line with "input:" and "Keyboard"
# Most regular keyboards also generate a log line that matches the second regex, but
# the duplicate events are removed by the filtering
regexes = [
    r".*input: .*Keyboard "
    r"(?!((mouse )?system control))(?!((mouse )?consumer control)).*",
    r".*input,hidraw.*keyboard (?!mouse)",
]

# Filter log_event_tuples based on regex matches and put them
# on the form the admin site expects:
# (timestamp, security_problem_uid, summary)
log_event_tuples = [
    (log_timestamp, security_problem_uid_template_var, log_event)
    for (log_timestamp, log_event) in log_event_tuples
    if any([re.search(regex, log_event, flags=re.IGNORECASE) for regex in regexes])
]

log_event_tuples = filter_boot_events(log_event_tuples, last_security_check)

log_event_tuples = filter_duplicate_events(log_event_tuples)

if not log_event_tuples:
    sys.exit()

csv_writer(log_event_tuples)
